### PR TITLE
Moved to actions, ONLY testing CPC and CPX

### PR DESCRIPTION
**Pull request by dherrada**

### CODE REVIEW

**Comment by dherrada** [comment]
@PaintYourDragon I'm not quite sure what to do about `mic_FFT_express.ino`, but there seems to be a similar EPioType issue going on with the Circuit Playground Express

**Comment by PaintYourDragon** [comment]
What’s puzzling me is that it’s in an Arduino header, not our code. I continue to be stumped by this one.

**Comment by dherrada** [comment]
Yeah, that is quite odd

**Comment by siddacious** [comment]
@dherrada that's the same error I got in https://github.com/adafruit/Adafruit_CircuitPlayground/pull/50

Please close that PR if you're going forward with this one. I don't care, but we certainly don't need two for the same thing :0

**Comment by dherrada** [comment]
@siddacious That's fair. I think it had something to do with some #includes needing to be reordered. I'll take a look at the other PR @PaintYourDragon was able to fix and try to do the same thing here

**Comment by dherrada** [comment]
Pretty sure this isn't working because of zeropdm, so once that gets merged and released, this should be fixed

**Comment by dherrada** [comment]
@ladyada So I think the issue here is that the CI is using an outdated version of zeroPDM it got here https://github.com/adafruit/arduino-board-index/blob/gh-pages/boards/adafruit-samd-1.5.14.tar.bz2

**Pull request closed without merging**
