### PR TITLE
Added Hello_CapTouch example

### PR DESCRIPTION
**Pull request by caternuson**
* Added a capacitive touch example, **Hello_CapTouch**, to the Hello_CircuitPlayground examples.
* Updated README.md with new info.

### CODE REVIEW

**Comment by ladyada** [comment]
can you update this to also work on CPX? the pads are named A1-A7 (only 7 pads)

**Comment by caternuson** [comment]
Probably should have some form of conditional check, for CPC vs CPX. Could probably do that with either `#ifdef`'s or try and use [.isExpress(](https://github.com/adafruit/Adafruit_CircuitPlayground/blob/master/Adafruit_CircuitPlayground.cpp#L360)). Got a pref?

**Comment by ladyada** [comment]
isExpress() is better if you can make it werk

**Comment by caternuson** [comment]
OK. Take a look now.

**Comment by caternuson** [comment]
i stashed this in a local branch if we want to PR it again

**Pull request closed without merging**
