### PR TITLE
actionified, formatted and doxy'd

### PR DESCRIPTION
**Pull request by siddacious**

### CODE REVIEW

**Comment by ladyada** [comment]
you'll need to adjust to test circuitplaygrounds (only)

**Comment by ladyada** [comment]
also bluefruit!

**Comment by siddacious** [comment]
@ladyada I added the bluefruit and fixed some missing deps however it's now failing for a reason I don't understand.

**Comment by ladyada** [comment]
plz use the adafruit cpx not arduino cpx definition

**Comment by siddacious** [comment]
@siddacious I updated the definitions however it seems to be still failing with the same errors

**Pull request closed without merging**
