### PR TITLE
Add external NeoPixel example

### PR DESCRIPTION
**Pull request by caternuson**
For #52 

cp_ext_neopix

### CODE REVIEW

**Comment by ladyada** [comment]
@caternuson can you add "Adafruit BusIO" to
https://github.com/adafruit/Adafruit_CircuitPlayground/blob/master/.travis.yml#L27
then CI should pass

**Comment by ladyada** [comment]
ok ping me if it doesnt pass

**Comment by caternuson** [comment]
Thanks! Right again :)

Should we have an issue for moving to actions?

**Comment by ladyada** [comment]
@dherrada is in process of doing this one, its one of the few stragglers!

**Pull request merged**
